//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwTools.PowerShortcut.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwTools.PowerShortcut.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel_Label {
            get {
                return ResourceManager.GetString("Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Opacity 的本地化字符串。
        /// </summary>
        public static string Change_Opacity {
            get {
                return ResourceManager.GetString("Change_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Size 的本地化字符串。
        /// </summary>
        public static string Change_Size {
            get {
                return ResourceManager.GetString("Change_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press one of the buttons to close the modal dialog 的本地化字符串。
        /// </summary>
        public static string Close_Modal {
            get {
                return ResourceManager.GetString("Close_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResExtension Type conversion failed. Id: {0}, Error: {1} 的本地化字符串。
        /// </summary>
        public static string ConversionErrorMessageFormatString {
            get {
                return ResourceManager.GetString("ConversionErrorMessageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入快捷键: 的本地化字符串。
        /// </summary>
        public static string Enter_Name {
            get {
                return ResourceManager.GetString("Enter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello 的本地化字符串。
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name may only contain alphabetic characters 的本地化字符串。
        /// </summary>
        public static string ID_NONUMVALUE {
            get {
                return ResourceManager.GetString("ID_NONUMVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name must contain at least one character 的本地化字符串。
        /// </summary>
        public static string ID_NOVALUEERROR {
            get {
                return ResourceManager.GetString("ID_NOVALUEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid assembly passed or assembly is not loaded. 的本地化字符串。
        /// </summary>
        public static string InvalidAssemblyExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidAssemblyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Static Binding Syntax 的本地化字符串。
        /// </summary>
        public static string InvalidStaticBindingSyntax {
            get {
                return ResourceManager.GetString("InvalidStaticBindingSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK_Label {
            get {
                return ResourceManager.GetString("OK_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Modal 的本地化字符串。
        /// </summary>
        public static string Open_Modal {
            get {
                return ResourceManager.GetString("Open_Modal", resourceCulture);
            }
        }
    }
}
